# Generated by Django 5.2.5 on 2025-08-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_marketdata_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PLN', 'PLN'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='PLN', max_length=3),
        ),
    ]
