# Generated by Django 5.2.5 on 2025-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0003_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'Purchase'), ('SELL', 'Sale')], max_length=10),
        ),
    ]
